# Generated by Django 4.2.1 on 2023-06-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('Recibido', 'Recibido'), ('En_proceso', 'En proceso'), ('Solucionado', 'Solucionado')], default='Recibido', max_length=20)),
            ],
        ),
    ]
